### ISSUE TITLE
Why don't you share on the marketplace? Is it possible to disallow some routes?

### ISSUE THREAD

**Issue by RomainMazB** [givingteam/oc-auth-plugin#13]
Hi Scott,

I've found this repo which could be helpful in a project I'm currently working on where I need to share an auth session between a Laravel app and an OctoberCMS installation.

I've looked on the marketplace and didn't find it there so I'm asking why? Does it contain some kind of issue or that kind of stuff? Maybe I can help.

Also a little question: is it possible to disallow some routes? Basically I just want to be open the login/logout routes. I know I can prevent users to access it by creating a custom routes.php with the same routes and require it before you're but if it's directly possible in your package, it's nice!

**Comment by scottbedard** [comment]
Hi, no this library is pretty stable, I've been using it for ages. As for why I don't publish it, 🤷. This plugin is generally used with [Vuetober themes](https://github.com/scottbedard/vuetober), which are pretty atypical for October. I feel like publishing this on the marketplace wouldn't be useful for most people, and might confuse traditional usage of RainLab.User.

As for enabling / disabling certain routes, I would totally accept a PR for this. The best way to do this would probably be by using config values. Sort of [like this](https://github.com/scottbedard/rainlab-user-api/blob/master/routes.php#L3), where we're using a config value to enable/disable the API as a whole 👍
